name: Deploy to Spaces
on:
  push:
    branches: [main]

jobs:
  sync-to-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          if [ -d "space" ]; then rm -rf space; fi
          git clone https://huggingface.co/spaces/yazoo1220/v2gif2img space || (
            git init space
            cd space
            git config --global init.defaultBranch main
            git remote add origin https://huggingface.co/spaces/yazoo1220/v2gif2img
            echo "# v2gif2img" > README.md
            git add README.md
            git commit -m "Initial commit"
            git push --set-upstream https://yazoo1220:$HF_TOKEN@huggingface.co/spaces/yazoo1220/v2gif2img main
            cd ..
          )
          cp -r * space/ || true
          cd space
          git add .
          git commit -m "Sync from GitHub" || echo "No changes to commit"
          git push https://yazoo1220:$HF_TOKEN@huggingface.co/spaces/yazoo1220/v2gif2img main
