name: Deploy to Hugging Face Spaces
on:
  push:
    branches: [main]

jobs:
  deploy-to-spaces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Install Hugging Face Hub CLI
          pip install huggingface_hub
          
          # Create Space if it doesn't exist
          python -c "
          from huggingface_hub import HfApi, SpaceHardware, SpaceStorage, SpaceSdk
          
          api = HfApi(token='$HF_TOKEN')
          
          # Check if space exists
          try:
              api.get_space_info('yazoo1220/v2gif2img')
              print('Space already exists')
          except Exception as e:
              print('Creating new space')
              api.create_space(
                  'yazoo1220/v2gif2img',
                  space_sdk=SpaceSdk.GRADIO,
                  space_hardware=SpaceHardware.CPU_BASIC,
                  space_storage=SpaceStorage.SMALL,
              )
          "
      
      - name: Prepare files for Space
        run: |
          mkdir -p space
          cp -r src space/
          cp app.py space/
          cp requirements.txt space/
          cp README-HF.md space/README.md
      
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd space
          git init
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update from GitHub Actions"
          
          # Push to Hugging Face Space
          git remote add origin https://yazoo1220:$HF_TOKEN@huggingface.co/spaces/yazoo1220/v2gif2img
          git push -f origin main
